PRPractice/jenny.txt
Creating a Pull Request Practice Directory So the team can practice pull requests at tomorrow's meeting. It will be deleted after 
Temporary Practice Directory, Will Be Deleted
- [+] I have performed a self-review of my code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] My changes generate no new warnings
- [+] I have assigned reviewers to this PR (Ooh fun idea! Will do!)
=> PR Practice

PRPractice/mylon.txt
=> mylon's first commit

event model - maggie - UNSURE WHERE TO PUT IM SORRY, src/types/dataModel/event model - maggie - UNSURE WHERE TO PUT IM SORRY
i did my best but i found I had a lot more questions than I originally thought during the last meeting. i think the meat and potatoes are here, but not the specifics ? idk man. 
i only published it now instead of asking tmrrw because I probably wont have access to my laptop tmrrw
=> event model schema - THIS IS NOT CORRECT

scripts/createTestData.script
Created a script file to be run on the mongoDB database to test volunteer and event cases.
- [1] New feature (non-breaking change which adds functionality)
- [ 1] My code follows the style guidelines of this project
- [ 1] I have performed a self-review of my code
- [ 1] I have commented my code, particularly in hard-to-understand areas
- [ 1] I have made corresponding changes to the documentation
- [ 1] My changes generate no new warnings
- [ 1] I have added tests that prove my fix is effective or that my feature works
- [ 1] I have assigned reviewers to this PR
=> Create test script for test data

src/server/models/testCases.json
I created a json file with 12 test cases for possible volunteers and 5 test cases for possible events.
I didn't really know what information to enter under "hours" so once the schema in updated to exactly what we need, I can change the json file if necessary.
- [ 1] New feature (non-breaking change which adds functionality)
- [1] My code follows the style guidelines of this project
- [1] I have performed a self-review of my code
- [1] I have commented my code, particularly in hard-to-understand areas
- [1] I have made corresponding changes to the documentation
- [1] My changes generate no new warnings
- [1] I have added tests that prove my fix is effective or that my feature works
- [1] I have assigned reviewers to this PR
=> Create json file with test cases.

scripts/createTestData.script
Updated the testData file to match the schema.
I feel like I remember you saying that I did not need to worry about the demographic very much yet, so I did not make any changes to any of the demographics. If you need me to make any other changes just let me know.
- [1 ] New feature (non-breaking change which adds functionality)
- [1 ] My code follows the style guidelines of this project
- [1 ] I have performed a self-review of my code
- [1 ] I have commented my code, particularly in hard-to-understand areas
- [1 ] I have made corresponding changes to the documentation
- [1 ] My changes generate no new warnings
- [1 ] I have added tests that prove my fix is effective or that my feature works
- [1 ] I have assigned reviewers to this PR
=> Updated the Volunteers and Events in the testData file.

src/server/models/Event.ts, src/types/dataModel/event.ts
Added day, manager, and description to the two events.ts files to match the schema. 
- [ 1] New feature (non-breaking change which adds functionality)
- [1 ] My code follows the style guidelines of this project
- [1 ] I have performed a self-review of my code
- [ 1] I have commented my code, particularly in hard-to-understand areas
- [ 1] I have made corresponding changes to the documentation
- [ 1] My changes generate no new warnings
- [1 ] I have added tests that prove my fix is effective or that my feature works
- [1 ] I have assigned reviewers to this PR
=> Update events files to match schema.

src/server/actions/Event.ts, src/types/dataModel/event.ts
Made createEvent function and zCreateEventRequest to create event
I am not certain this works as I am currently unable to test it but it compiled with npm
And with the zod was partial() the right way to implement?
=> updated two files to make action create event

src/server/actions/Volunteer.ts, src/types/dataModel/volunteer.ts
- [ 1] New feature (non-breaking change which adds functionality)
- [ 1] My code follows the style guidelines of this project
- [1 ] I have performed a self-review of my code
- [1 ] I have commented my code, particularly in hard-to-understand areas
- [1 ] I have made corresponding changes to the documentation
- [1 ] My changes generate no new warnings
- [1 ] I have assigned reviewers to this PR
=> Created function to return all volunteers phone numbers.

src/server/actions/Event.ts
=> 52-add deleteEvent

src/app/api/events/route.ts
This should be correct for creating an event 
#68 
I don't remember how to test it, but based on the volunteer endpoint / these two should work similarly.
=> #68 create event api endpoint

package-lock.json, package.json, src/app/api/event/route.ts, src/types/dataModel/event.ts
=> fixed create event

src/app/api/eventVolunteer/route.ts, src/types/dataModel/eventVolunteer.ts
=> created createEventVolunteer API endpoint

src/app/api/eventVolunteer/[eventVolunteerId]/route.ts, src/server/actions/EventVolunteer.ts, src/types/dataModel/eventVolunteer.ts
=> fixed delete event volunteer action and created delete volunteer API

src/server/actions/EventVolunteer.ts, src/types/dataModel/eventVolunteer.ts, src/views/NewVolunteerView/index.tsx
Created an action that would first check to see if a volunteer is already signed in, and if they are not, it will sign them in.
- #13
I don't actually know if this works yet. It will need to be tested once I have the api endpoint created I would assume.
- [ 1] New feature (non-breaking change which adds functionality)
- [ 1] My code follows the style guidelines of this project
- [ 1] I have performed a self-review of my code
- [ 1] I have commented my code, particularly in hard-to-understand areas
- [ 1] I have made corresponding changes to the documentation
- [ 1] My changes generate no new warnings
- [ 1] I have added tests that prove my fix is effective or that my feature works
- [ 1] I have assigned reviewers to this PR
=> First attempt at creating an action.

src/server/actions/Event.ts
=> 47 get upcoming events

src/server/actions/Event.ts, src/server/actions/EventVolunteer.ts, src/types/dataModel/eventVolunteer.ts
added getEvent function, and also added three "}"s that seemed to have disappeared... must've happened during merging but not sure
#92
=> 92 -  getEvent action 

src/server/actions/EventVolunteer.ts, src/server/actions/Volunteer.ts, src/types/dataModel/eventVolunteer.ts
made actions and necessary zods for get all volunteers and volunteer checkout
#14 
#49 
I dont know if i made the get all volunteers action correctly
=> Volunteer Checkout Action & Get All Volunteers

src/server/actions/Volunteer.ts
added getVolunteer based on getEvent... if one needs to be fixed then the other will be an issue too 
#94
=> 94 getVolunteer action 

src/app/api/event/[eventId]/route.ts
=> DELETE EVENTS API

src/server/actions/Event.ts, src/types/dataModel/eventVolunteer.ts
=> issue 54 added update event

package-lock.json, package.json, src/app/api/eventVolunteer/[eventVolunteerId]/routes.ts, src/app/api/eventVolunteer/route.ts, src/server/actions/EventVolunteer.ts, src/types/dataModel/eventVolunteer.ts
Created Api Endpoint.
- #77 
-->
- [*] New feature (non-breaking change which adds functionality)
=> 59 volunteer check in api endpoint

src/app/api/volunteer/[volunteerId]/route.ts
Created an API delete endpoint for volunteer
- #69 
There was the issue with .next and eventVolunteer (the zentity) so warning I had to comment out stuff
=> delete vol api endpoint

src/app/api/event/[eventId]/route.ts
Update event api endpoint
- #60
- [*] New feature (non-breaking change which adds functionality)
=> Created Api Endpoint for updating event.

src/components/NavBar/index.tsx
Adds basic half-styled nav bar. As in things are where they should be, but the fonts and colors are wrong and no logo
#115
=> 115 - add basic half-styled nav bar

src/app/sign-in/page.tsx
Created a page that will be the sign in page.
=> Created Sign-In Page

src/app/events/page.tsx
Added the src/app/events dir and its associated page.tsx file
#112 
N/A
=> Added 'events' dir and the associated page.tsx

src/app/adminDatabse/page.tsx
=> made admin data base page

src/app/contactinfo/page.tsx
=> contact info page created

src/app/userprofile.tsx
Added page for user profile
- #111
=> added user profile page

src/app/landingPage/page.tsx
=> Created Landing Page.

src/server/actions/Event.ts
=> created action getVolunteerEvents

src/app/landingPage/page.tsx, src/components/EventList/index.tsx, src/server/actions/Event.ts
=> created VERY minimal Event list

src/server/actions/Volunteer.ts, src/server/models/Volunteer.ts, src/types/dataModel/volunteer.ts
=> added all the extra fields to data model and db model

src/app/events/page.tsx, src/components/EventList/index.tsx, src/server/actions/Event.ts
Added volunteer's events list and upcoming events list to the events page
#135
=> 135 add events components to events page

src/app/landingPage/page.tsx, src/components/LandingPageHelpButton/index.tsx
Created a help button for landing page use. Currently has filler text and is not stylized correctly.
#121
=> Created help button component

src/app/api/eventVolunteer/[eventVolunteerId]/route.ts, src/app/userprofile/page.tsx, src/server/actions/Event.ts, src/server/actions/EventVolunteer.ts, src/types/dataModel/eventVolunteer.ts
=> Repair api

src/app/userprofile/page.tsx
Created a page to show Name, email, and phone number.
I am not sure what all fields this page needs. Please let me know if you have a list of stuff.
- [ x] I have assigned reviewers to this PR
=> Created Profile page.

src/app/events/page.tsx, src/components/UpcomingEventsList/index.tsx, src/components/VolunteerEventsList/index.tsx, src/server/actions/Event.ts
=> fixed event list and something else... cant remember

src/app/api/volunteer/route.ts, src/app/contactinfo/page.tsx, src/components/AdminContactInfo/index.tsx, src/server/actions/Volunteer.ts
The contact info page is now displaying the name, email, and number of all admins currently in the database. I added this stylized page (taking inspiration from the sign-in page), and also went ahead and created the function and route that will automatically retrieve the admins instead of one at a time by their ID.
#118 
No questions.
=> gh-118 Added contact info page, and function that retrieves all admins

src/app/userprofile/page.tsx, src/components/UserProfilePage/index.tsx
Created userProfile form template with edit capabilities. It also displays user data.
All of the sources said to make the form client side because of all the re-renders. If you want this to be changed, let me know.
=> Created user profile form.

src/components/SignUpButton/index.tsx, src/components/UpcomingEventsList/index.tsx, src/types/dataModel/volunteer.ts
=> Created sign-up button.

src/components/EventList/index.tsx, src/components/MoreInfoButton/index.tsx, src/components/UpcomingEventsList/index.tsx
Second attempt at more info button
- #139 
Cannot get anything to render, database issue?
=> more info button take 2

src/app/adminDatabase/page.tsx, src/app/contactinfo/page.tsx, src/app/event/page.tsx, src/app/events/page.tsx, src/app/page.tsx, src/app/userprofile/page.tsx, src/components/NavBar/index.tsx
=> routed navbar

src/app/manageEvent/[eventId]/page.tsx, src/components/DeleteEventButton/index.tsx
=> delete button functionality added

src/app/manageEvent/[eventId]/page.tsx, src/components/EditEventButton/index.tsx, src/components/EditEventForm/index.tsx, src/views/EditEventView/index.tsx
need to clear errors later but dont seem to affect anything
#143
=> Implemented edit button functionality

src/app/userprofile/page.tsx, src/components/MoreParticipantInfo/index.tsx, src/components/RegisteredVolsList/index.tsx, src/components/UserProfilePage/index.tsx, src/server/actions/Volunteer.ts
=> this is ugly but it gets the job done

src/app/manageEvent/[eventId]/page.tsx, src/components/CopyEmailsButton/index.tsx, src/components/CopyPhoneNumbersButton/index.tsx
=> add CopyPhoneNumbersButton and CopyEmailsButton

src/app/userprofile/page.tsx, src/components/NavBar/index.tsx
Added help and its modal, changed navbar, and fixed user profile (volunteer to volunteer entity)
- #166
=> added help and fixed user profile? idk

package-lock.json, package.json, src/app/database/page.tsx, src/app/userprofile/page.tsx, src/components/CSVButton/index.tsx
=> Added Download CSV button.

src/app/database/page.tsx
=> Added copy email and phone number buttons.

src/components/CancelSignUpButton/index.tsx, src/components/SignUpButton/index.tsx
=> made page refresh after sign up and cancel

src/app/events/page.tsx, src/components/CancelSignUpButton/index.tsx, src/components/ManageEventPage/index.tsx, src/components/MoreInfoButton/index.tsx, src/components/NavBar/index.tsx, src/components/SignUpButton/index.tsx, src/components/UpcomingEventsList/index.tsx, src/components/VolunteerEventsList/index.tsx
I fixed the formatting! 
- #171
=> fixed the formatting!!!! quit complaining mylon

src/app/api/volunteer/search/route.ts, src/app/database/page.tsx, src/app/manageEvent/[eventId]/page.tsx, src/components/DatabaseVolunteersList/index.tsx, src/components/RegisteredVolsList/index.tsx, src/components/VolunteerSearchBar/index.tsx
Added search bar to both the manage event page and the database page.
#207
=> 207 create search volunteers component for the manage event page and database page

src/app/events/page.tsx, src/components/NavBar/index.tsx
Fixed the nav bar bug, additionally the events page had weird spacing issues when you made the screen smaller so i fixed that as well
- #198 
n/a
=> fixed nav bar bug, also fixed events page spacing in small screen

.eslintrc.json, .lintstagedrc.js, src/app/page.tsx, tsconfig.json
=> Linting error

src/server/actions/Event.ts, src/server/actions/EventVolunteer.ts, src/server/actions/Volunteer.ts
Added dev error checking for the server actions.
-->
Is this what you were looking for? Or were you looking to make it to where users would get elegant errors when they put a wrong username or something?
=> Added dev error checking

src/app/database/page.tsx, src/app/events/page.tsx, src/app/manageEvent/[eventId]/page.tsx, src/components/AddEventButton/index.tsx, src/components/AddVolunteerButton/index.tsx, src/components/EditEventButton/index.tsx, src/components/EditEventForm/index.tsx, src/components/NewEventForm/index.tsx, src/server/actions/Volunteer.ts, src/views/EditEventView/index.tsx, src/views/NewEventView/index.tsx, src/views/NewVolunteerView/index.tsx
Added buttons listed in the issue.
Edited files listed in issue but github thinks I edited more as I used the same branch as the previous pull request.
So basically this pull request is issue #232 and issue #236 
#232 
#236 
- [] I have made corresponding changes to the documentation
- [ x] I have assigned reviewers to this PR
=> Add buttons volunteer events#232

src/app/manageEvent/[eventId]/page.tsx, src/components/AddEventButton/index.tsx, src/components/EditEventButton/index.tsx, src/components/EditEventForm/index.tsx, src/components/NewEventForm/index.tsx, src/server/actions/Volunteer.ts, src/views/EditEventView/index.tsx, src/views/NewEventView/index.tsx
Added dropdown manager for add event / edit event form. Only difference is edit event autopopulates with event's manager while add event doesn't.
Edited files:
src/app/manageEvent/[eventId]/page.tsx
src/components/AddEventButton/index.tsx
src/components/EditEventButton/index.tsx
src/components/EditEventForm/index.tsx
src/components/NewEventForm/index.tsx
src/server/actions/Volunteer.ts
src/views/EditEventView/index.tsx
src/views/NewEventView/index.tsx
Files were edited so getManagerVolunteers() data was passed along the chain. Allowing me to use the data on the forms.
#236
=> finished dropdown

src/app/events/page.tsx, src/app/manageEvent/[eventId]/page.tsx, src/server/actions/Volunteer.ts
extended fix by creating an function that grabs both admins and managers.
added admins to dropdown by creating a function that grabs both admins and managers.
#236
=> added admins to dropdown

src/components/LoginButton/index.tsx, src/components/welcome/index.tsx
=> login button on welcome page

src/app/userprofile/page.tsx, src/components/DatabaseVolunteersList/index.tsx, src/components/MoreParticipantInfo/index.tsx, src/components/RegisteredVolsList/index.tsx, src/components/UserProfilePage/index.tsx
Add currentUser param to UserProfilePage and a check for admin status to display Membership Data section of UserProfilePage
#227
=> 227 conditionally render user profile admin only fields

src/server/models/Volunteer.ts, src/types/dataModel/volunteer.ts, src/views/NewVolunteerView/index.tsx
=> adds profileFinished to new Volunteers

src/app/manageEvent/[eventId]/page.tsx, src/components/MoreInfoButton/index.tsx, src/server/actions/Event.ts, src/server/actions/EventVolunteer.ts, src/server/models/Event.ts, src/types/dataModel/event.ts, src/types/forms/event.ts
Made it so that number of volunteers is kept up with and displayed.
194
=> Made it so that number of vols signed up for an event is shown.

src/app/global.styles.css, src/app/layout.tsx, src/app/page.tsx
=> created style sheet

src/components/CSVButton/index.tsx
Added a map to remove the _id and the __v  from the csv exported files
- #242
=> removed unwanted fields from csv

src/app/api/auth/[...nextauth]/route.ts, src/middleware.ts, src/next-auth.d.ts
Changed auth to add a role based on mongoDB database on login. (will need to relogin if you are already logged in)
Added reroutes if user does not have required roles for manageEvent (admin / manager) or database (admin).
Tested by changing my role to Volunteer | Manager | Admin. 
#244 
#223 
You will need to login again if you are still logged in (only one time to trigger the role allocator).
=> auth handling for manageEvent and database

src/app/global.styles.css, src/app/manageEvent/[eventId]/page.tsx, src/components/MoreParticipantInfo/index.tsx, src/components/RegisteredVolsList/index.tsx, src/components/UserProfilePage/index.tsx, src/components/VolunteerSearchBar/index.tsx
adjusted manage event styling to fit changes requested and moved everything to global css file
- #268 
- #269 
- #270 
- #271
Fix overlapping profile modal?
=> changed the styling for manage event page

src/components/LoginButton/index.tsx, src/components/welcome/index.tsx
Made welcome message dynamic so that it does not prompt user to sign in after they are signed in.
=> Made welcome message dynamic

src/app/api/auth/[...nextauth]/route.ts, src/app/database/page.tsx, src/app/global.styles.css, src/components/DatabaseVolunteersList/index.tsx, src/components/MoreParticipantInfo/index.tsx, src/components/UserProfilePage/index.tsx, src/components/VolunteerSearchBar/index.tsx
Database adjustments have been made, also I improved the user profile popout (so if we could use these changes instead of the ones I made prior that would be lovely!)
- #272 
- #273 
- #274 
- #275 
The issue with the user profiles staying open is still present
=> database css changes (user profile popout improved)

src/components/EventList/index.tsx, src/components/MoreInfoButton/index.tsx, src/components/UpcomingEventsList/index.tsx
=> 276 - gets manager's name using volunteer id for more info button

src/components/NavBar/index.tsx
=> remove border radius from nav bar

src/app/events/page.tsx, src/app/global.styles.css, src/app/manageEvent/[eventId]/page.tsx, src/components/AddEventButton/index.tsx, src/components/AddVolunteerButton/index.tsx, src/components/RegisteredVolsList/index.tsx
Changed all inline styling for requested files to css in the global files, additionally there were some changes I made that got lost in merging somehow? so i added those back to fix the styling. 
- #294
=> fixed styling to css

src/app/api/auth/[...nextauth]/route.ts, src/components/UserProfilePage/index.tsx, src/middleware.ts, src/next-auth.d.ts
=> Unfilled form redirect

src/app/global.styles.css, src/components/NavBar/index.tsx
Added styling to the Navbar component.
=> Finished CSS Task 5

src/components/AddEventButton/index.tsx, src/components/LoginButton/index.tsx, src/components/ManageEventPage/index.tsx, src/components/welcome/index.tsx
Hides Add Event and Manage event if userRole == 'Volunteer'. (if they add any roles in the future may need to change).
Hides login button and text if session is not found (not logged in)
=> hiding add event, manage event, login button

src/app/global.styles.css, src/components/LoginButton/index.tsx, src/components/VolunteerEventsList/index.tsx, src/components/welcome/index.tsx
=> changed inline styles to css and fixed login button

src/app/global.styles.css
=> added some css variables

src/app/global.styles.css
=> Removed the fixed postion of the logo

src/app/global.styles.css, src/components/DeleteEventButton/index.tsx, src/components/EditEventButton/index.tsx, src/components/EditEventForm/index.tsx, src/components/EventList/index.tsx
=> Changed the inline styling of some components to CSS

src/app/global.styles.css, src/app/page.tsx, src/components/AdminContactInfo/index.tsx, src/components/LoginButton/index.tsx, src/components/welcome/index.tsx
=> jen did more code

src/app/global.styles.css, src/app/manageEvent/[eventId]/page.tsx, src/components/CheckInButton/index.tsx, src/components/CopyEmailsButton/index.tsx, src/components/CopyPhoneNumbersButton/index.tsx, src/components/DeleteEventButton/index.tsx, src/components/EditEventButton/index.tsx, src/components/RegisteredVolsList/index.tsx
=> Manage event mobile responsive

src/app/global.styles.css, src/components/AdminContactInfo/index.tsx, src/components/CancelSignUpButton/index.tsx
Added global styling for Admin Contact Info and Cancel Signup Button components
- #295
=> converted inline to css for #2

src/app/global.styles.css
Logo is now centered on smaller screens and it works 
- #316 
The hamburger menu works fine, needed no changes.
=> centered nav bar logo

src/app/database/page.tsx, src/app/global.styles.css, src/app/manageEvent/[eventId]/page.tsx, src/app/userprofile/page.tsx, src/components/CheckInButton/index.tsx, src/components/DatabaseContent/index.tsx, src/components/DatabaseVolunteersList/index.tsx, src/components/ManageEventContent/index.tsx, src/components/MoreParticipantInfo/index.tsx, src/components/RegisteredVolsList/index.tsx, src/server/actions/Event.ts, src/types/dataModel/event.ts, src/types/dataModel/volunteer.ts
=> More manage event mobile responsiveness

src/app/global.styles.css, src/app/userprofile/page.tsx, src/components/NavBar/index.tsx, src/components/UserProfilePage/index.tsx
=> 301-mobile compliance user profile page

src/app/global.styles.css, src/components/NewVolunteerForm/index.tsx, src/components/SignUpButton/index.tsx, src/components/UpcomingEventsList/index.tsx, src/components/UpdateVolunteerForm/index.tsx
Converted all files from inline CSS.
Except src/components/UpdateVolunteerForm/index.tsx.
The text sx was weird when I was trying to convert so I left it.
#307
=> global ss conversion

src/components/NavBar/index.tsx
=> cond render on nav bar

src/components/UserProfilePage/index.tsx
=> fixed update for finishedProfile

src/app/global.styles.css, src/components/AdminContactInfo/index.tsx, src/components/LoginButton/index.tsx, src/components/NavBar/index.tsx, src/components/welcome/index.tsx
=> Fixxed Aesthetics of Front Page (desktop and mobile compatible)

src/app/global.styles.css, src/components/AddVolunteerButton/index.tsx, src/components/DatabaseContent/index.tsx
I have updated the css styles for the database page so that the screen looks correct on phones and normal screens.
I think I might have needed to do something with the user profile pop-up but I will ask Mylen about that this Friday.
=> Fixed Database Page Styles for phones.

src/app/global.styles.css
=> fix blue signup

src/components/UserProfilePage/index.tsx
The user profile now forces you to fill out the necessary fields even when logging in or refreshing or saving
- #356
=> fixed user profile issues with unpopulated fields

src/components/NavBar/index.tsx
fix nav bar button showing for managers
=> fix nav bar button showing for managers

src/app/events/page.tsx, src/components/CancelSignUpButton/index.tsx, src/components/ManageEventButton/index.tsx, src/components/SignUpButton/index.tsx, src/components/UpcomingEventsList/index.tsx, src/components/VolunteerEventsList/index.tsx, src/server/actions/Event.ts, src/types/dataModel/event.ts, src/types/dataModel/eventVolunteer.ts
=> Andrew doing things (+ Mylon + Randy)

src/app/auth/error/page.tsx, src/app/userprofile/page.tsx, src/components/NavBar/index.tsx
1. remove profile icon in the nav bar when no user is logged in
2. redirects to home page if unlogged in user attempts to access profile page
3. "try again" page (/auth/error page) redirects to home page upon successful login attempt
closes #330
=> 330-fix try again redirect

src/app/global.styles.css
=> Adjusted CSS for manage event page, made it so the page no longer scrolls and fixed the issues that arose from this

src/app/global.styles.css, src/app/userprofile/page.tsx
=> Added a warning for when the user profile is not completed, also mobile compliant

src/views/EditEventView/index.tsx, src/views/NewEventView/index.tsx, src/views/NewVolunteerView/index.tsx
=> Css changes for new event/edit event/new user

src/app/events/page.tsx, src/app/global.styles.css, src/components/DatabaseContent/index.tsx
=> 350 database user profile exit button

src/app/events/page.tsx, src/app/global.styles.css, src/components/MoreInfoButton/index.tsx, src/components/UpcomingEventsList/index.tsx, src/server/actions/Event.ts, src/types/dataModel/event.ts, src/types/dataModel/volunteer.ts
=> did more than one issue

src/app/global.styles.css, src/components/UserProfilePage/index.tsx
=> fixed warning bar

src/app/global.styles.css, src/components/DatabaseContent/index.tsx, src/components/ManageEventContent/index.tsx, src/components/NavBar/index.tsx
=> One branch to rule them all
